Readmore/urls.py
from django.contrib import admin
from django.urls import path, include
from readmore_app import urls as readmore_app_urls
from readmore_app import views as readmore_app_views
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('readmore/', include(('readmore_app.urls', 'readmore_app'), namespace="readmore_app"), name="readmore_app_patterns"),
    path('', lambda request: redirect('readmore/', permanent=False)),
]

readmore_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index_full_link'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('login/<int:account_created>/', views.login, name='login_account_created'),
    path('logout/', views.logout, name='logout'),
    path('notifications/', views.notifications, name='notifications'),
    path('profile/<int:profile_id>/', views.profile, name='profile'),
    path('create_club/', views.create_club, name='create_club'),
    path('club/<int:club_id>/', views.club, name='club'),
    path('club_chat/<int:club_id>/', views.club_chat, name="club_chat"),
    path('friend_list/<int:profile_id>/', views.friend_list, name='friend_list'),
    path('user_search_results/', views.user_search_results, name="user_search_results"),
    path('book_clubs/', views.book_clubs, name="book_clubs"),
    path('club_members/<int:club_id>/', views.club_members, name='club_members'),
    path('invite_to_club/<int:club_id>/', views.invite_to_club, name='invite_to_club'),
    path('view_book/<str:book_isbn>/', views.view_book, name='view_book'),
    path('search_book/', views.search_book, name="search_book"),
    path('club_library/<int:club_id>/', views.club_library, name="club_library"),
    path('create_club_post/<int:club_id>/', views.create_club_post, name="create_club_post"),
    path('create_profile_post/<int:profile_id>/', views.create_profile_post, name="create_profile_post"),
	path('reading_log/', views.reading_log, name='reading_log'),
    path('reading_log/<int:profile_id>', views.reading_log_friend_view, name="reading_log_friend_view"),
    path('view_post/<int:post_id>/', views.view_post, name='view_post'),
    path('view_post/<int:post_id>/<int:highlight>/', views.view_post, name="view_post_highlighted_comment"),
    path('review_book/<str:book_isbn>/', views.create_review_post, name='create_review_post'),
    path('messages/', views.messages, name='messages_no_id'),
    path('messages/<int:friend_id>/', views.messages, name='messages'),
    path('book_forum/<str:book_isbn>/', views.book_forum, name='book_forum'),
    path('create_book_forum_post/<str:book_isbn>/', views.create_book_forum_post, name="create_book_forum_post"),
    path('club_schedule/<int:club_id>/', views.club_schedule, name='club_schedule'),
]

# AJAX url patterns
urlpatterns.extend(
    [
    path('ajax/notifications/<int:notification_id>/', views.delete_notification, name="delete_notification"),
    path('ajax/friend/', views.process_friend, name='process_friend'),
    path('ajax/get_friend_count/<int:user_id>/', views.get_friend_count, name="get_friend_count"),
    path('ajax/leave_club/<int:club_id>/', views.leave_club, name="leave_club"),
    path('ajax/kick_member/<int:club_id>/<int:member_id>/', views.kick_member, name="kick_member"),
    path('ajax/invite_member/<int:club_id>/<int:friend_id>/', views.invite_member, name="invite_member"),
    path('ajax/invite_nonfriend/<int:club_id>/<str:user>/', views.invite_nonfriend, name="invite_nonfriend"),
    path('ajax/join_club/<int:club_id>/', views.join_club, name="join_club"),
    path('ajax/remove_from_library/<int:club_id>/<int:club_book_id>/', views.remove_from_library, name='remove_from_library'),
    path('ajax/add_to_library/<int:club_id>/<str:isbn>/', views.add_to_library, name='add_to_library'),
    path('ajax/dolike/<int:post_id>/', views.do_like, name="do_like"),
    path('ajax/make_comment/<int:post_id>/', views.make_comment, name="make_comment"),
    path('ajax/remove_from_user_library/<int:book_id>/', views.remove_from_user_library, name='remove_from_user_library'),
    path('ajax/add_to_user_library/<str:isbn>/', views.add_to_user_library, name='add_to_user_library'),
    path('ajax/delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('ajax/save_bio/<int:user_id>/', views.save_bio, name='save_bio'),
    path('ajax/delete_meeting/<int:meeting_id>/', views.delete_meeting, name='delete_meeting'),
    ]
)

readmore_app/models.py
import re
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone

# User model extension for adding more attributes
class UserExt(User):
    user_friends = models.ManyToManyField('UserExt', related_name="friends")
    user_birthdate = models.DateField()
    user_bio = models.TextField(default="This user hasn't written a bio :(")
    user_pending_friends = models.ManyToManyField('UserExt', related_name="pending_friends")
    user_reading_log = models.ManyToManyField('ReadingLogBook', related_name="reading_log")
    
    def num_notifications(self):
        return Notification.objects.filter(notification_user=self).count()
        
    def reading_log_isbns(self):
        return [book.isbn for book in self.user_reading_log.all()]

class Notification(models.Model):
    notification_id = models.AutoField(primary_key=True)
    notification_type = models.CharField(max_length=10000, blank=True)
    notification_user = models.ForeignKey(UserExt, on_delete=models.CASCADE)
    notification_title = models.CharField(max_length=10000)
    notification_time = models.DateTimeField(auto_now_add=True)
    notification_link = models.CharField(max_length=10000, blank=True)
    notification_link_text = models.CharField(max_length=10000, blank=True)
    notification_message = models.TextField()

class Club(models.Model):
    club_id = models.AutoField(primary_key=True)
    club_name = models.CharField(max_length=100)
    club_description = models.TextField(blank=True)
    club_owner = models.ForeignKey(UserExt, on_delete=models.CASCADE)
    club_users = models.ManyToManyField(UserExt, related_name="user_clubs")
    club_pending_invites = models.ManyToManyField('UserExt', related_name="pending_invites", blank=True)
    club_library = models.ManyToManyField('ClubBook', related_name='clubs', blank=True)

class ClubBook(models.Model):
    isbn = models.CharField(max_length=20)
    time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.isbn)

class ReadingLogBook(models.Model):
    isbn = models.CharField(max_length=13)
    time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.isbn)

class Chat(models.Model):
    chat_id = models.AutoField(primary_key=True)
    chat_user = models.ForeignKey(UserExt, null=True, on_delete=models.SET_NULL)
    chat_time = models.DateTimeField(auto_now_add=True)
    chat_type = models.CharField(default="chat", blank=False, null=False, max_length=20)
    chat_message = models.TextField()

class ClubChat(Chat):
    chat_destination = models.ForeignKey(Club, on_delete=models.CASCADE)

class PM(Chat):
    chat_pm_identifier = models.CharField(max_length=100)

class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    post_user = models.ForeignKey(UserExt, models.CASCADE)
    post_title = models.TextField()
    post_text = models.TextField(blank=True)
    post_img = models.TextField(blank=True)
    post_likes = models.ManyToManyField(UserExt, related_name="likes", blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    
    def setup_info(self, info_user, info_title=None, info_text="", info_image="", info_date=datetime.now()):
        """
        Used for initializing the basic values of a Post
        """
        
        self.post_user = info_user
        self.post_title = info_title or f"Post by {self.post_user.username}"
        self.post_text = info_text
        self.post_img = info_image
        self.post_date = info_date
        
        # Escape HTML Characters in Post's Message
        self.post_text = self.post_text.replace('&', "&amp;")
        self.post_text = self.post_text.replace('<', "&lt;")
        self.post_text = self.post_text.replace('>', "&gt;")
        self.post_text = self.post_text.replace('"', "&quot;")
        self.post_text = self.post_text.replace("'", "&#39;")
        
        # Save Post
        self.save()
        
        # Tagged Users in Post's Message
        tag_list = re.findall("@[a-zA-Z_\-0-9]+", self.post_text)
        print(tag_list)
        tag_user_set = set()
        for tag in tag_list:
            try:
                tag_username = tag[1:]
                tag_user = UserExt.objects.get(username__iexact=tag_username)
                
                # Link to Tagged User's Profile
                self.post_text = self.post_text.replace(tag, f'<a href="/readmore/profile/{tag_user.id}">&#64;{tag_username}</a>', 1)
                self.save()
                
                # Notify Tagged User
                if tag_user != self.post_user and tag_user not in tag_user_set:
                    tag_user_set.add(tag_user)
                    notify_tag = Notification()
                    notify_tag.notification_type = f"tag"
                    notify_tag.notification_user = tag_user
                    notify_tag.notification_title = f"You Were Tagged by {self.post_user.username}"
                    notify_tag.notification_link = f"/readmore/view_post/{self.post_id}/"
                    notify_tag.notification_link_text = f"{self.post_title}"
                    notify_tag.notification_message = f"{self.post_user.username} has tagged you in their post.  Click the link above to see."
                    notify_tag.save()
                    
            except ObjectDoesNotExist:
                pass
    
    def date_formatted(self):
        return self.post_date.strftime("%m/%d/%Y %I:%M:%S %p")
    
    def get_likes(self):
        return len(self.post_likes.all()) - len(self.post_dislikes.all())

class ClubPost(Post):
    post_club = models.ForeignKey(Club, on_delete=models.CASCADE)

class ProfilePost(Post):
    post_profile_user = models.ForeignKey(UserExt, on_delete=models.CASCADE)

class Comment(Post):
    post_parent = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

class ReviewPost(Post):
    post_isbn = models.TextField()
    post_rating = models.IntegerField()
	
class BookForumPost(Post):
    # This NEEDS to be named something other than post_isbn.  Each subclass of post needs a distinct attribute.
    post_book_isbn = models.TextField()
    
class Meeting(models.Model):
    meeting_id = models.AutoField(primary_key=True)
    meeting_name = models.CharField(max_length=100, blank=True)
    meeting_description = models.TextField(blank=True)
    meeting_club = models.ForeignKey(Club, models.CASCADE)
    meeting_time = models.DateTimeField()
    
    @staticmethod
    def update_meetings(club_id):
        club = Club.objects.get(pk=club_id)
        club_meetings = Meeting.objects.filter(meeting_club=club)
        delete_ids = []
        for meeting in club_meetings:
            if meeting.meeting_time < timezone.now():
                delete_ids.append(meeting.meeting_id)
        for id in delete_ids:
            Meeting.objects.get(pk=id).delete()
        return bool(delete_ids)

readmore_app/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from .models import UserExt
import re
from datetime import date, timedelta, datetime

class club_post(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'size':50}), validators=[validators.RegexValidator(regex="^[a-zA-Z_\-0-9].{2,99}$", message="A valid post title less than 100 characters must be provided.")])
    image = forms.CharField(required=False, widget=forms.TextInput(attrs={'size':50}))
    text = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'style': 'resize: vertical;'}), required=False)

class profile_post(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'size':50}), validators=[validators.RegexValidator(regex="^[a-zA-Z_\-0-9].{2,99}$", message="A valid post title must be provided.")])
    image = forms.CharField(required=False, widget=forms.TextInput(attrs={'size':50}))
    text = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'style': 'resize: vertical;'}), required=False)


class login(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'maxlength': "50"}))
    password = forms.CharField(widget = forms.PasswordInput)
    def clean_username(self):
        username = self.cleaned_data['username']
        if not UserExt.objects.filter(username__iexact=username).exists():
            raise ValidationError(f"{username} is not a valid user.")
        else:
            return username


class register(forms.Form):
    username = forms.CharField()
    first_name = forms.CharField(validators=[validators.RegexValidator(regex="^[a-zA-Z -]+$", message="Invalid entry for first name.")])
    last_name = forms.CharField(validators=[validators.RegexValidator(regex="^[a-zA-Z -]+$", message="Invalid entry for last name.")])
    email = forms.EmailField(validators=[validators.EmailValidator(message="A valid email must be provided.")])
    birthdate = forms.DateField(widget=forms.SelectDateWidget(years=[*range(1900, datetime.now().year)]))
    password = forms.CharField(widget = forms.PasswordInput(), required=True)
    confirm_password = forms.CharField(widget = forms.PasswordInput(), required=True)

    def clean_username(self):
        username = self.cleaned_data['username']
        if UserExt.objects.filter(username__iexact=username).exists():
            raise ValidationError("Username already in use.")
        if not username or not re.match("^[a-zA-Z_\-0-9]+[a-zA-Z_\-0-9]*$", username):
            raise ValidationError("A valid username must be provided.")
        if len(username) > 50:
            raise ValidationError("Username must be less than or equal to 50 characters.")
        else:
            return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserExt.objects.filter(email=email.lower()).exists():
            raise ValidationError("Email already in use.")
        else:
            return email
    
    def clean_birthdate(self):
        birthdate = self.cleaned_data['birthdate']
        if type(birthdate) is type(None):
            raise ValidationError("Birthdate must be entered in the form MM/DD/YYYY.")
        elif birthdate > date.today() - timedelta(days=1095) or birthdate < date(1900, 1, 1):
            raise ValidationError("A valid birthdate must be provided.")
        else:
            return birthdate
    
    # this really should be clean_password but this validation requires two fields
    def clean(self):
        cleaned_data=super().clean()
        password = cleaned_data.get('password') or ""
        print(password)
        confirm_password = cleaned_data.get('confirm_password') or ""
        if not re.match("^[^\s]{8}[^\s]*$", password):
            raise ValidationError("Password must be 8 characters or more in length")
        if password != confirm_password:
            raise ValidationError("Passwords do not match.")
        else:
            return cleaned_data


class club(forms.Form):
	name = forms.CharField(validators=[validators.RegexValidator(regex="^[a-zA-Z_\-0-9].{2,99}$", message="A valid book club name must be provided.")])
	description = forms.CharField(validators=[validators.RegexValidator("^[a-zA-Z_\-0-9].{0,300}$", message="Description must be 300 or fewer characters.")], widget=forms.Textarea(attrs={'cols': 50, 'style': 'resize: vertical;', 'min-height': '50px'}), required=False)


class reading_log(forms.Form):
	isbn = forms.CharField(validators=[validators.RegexValidator(regex="^(?=(?:[0-9]){10}(?:(?:[0-9]){3})?$)[0-9]+$", message="Invalid entry for ISBN.")])


class review_post(forms.Form):
    review_text = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'style': 'resize: vertical;'}), required=False)
    rating = forms.ChoiceField(choices=((1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10)))

class meeting(forms.Form):
    meeting_name = forms.CharField(widget=forms.TextInput(attrs={'size':50}), validators=[validators.RegexValidator(regex="^.{0,100}$", message="Meeting name must be less than 100 characters.")], required=False)
    meeting_date = forms.DateField(widget=forms.SelectDateWidget(years=[*range(datetime.now().year, datetime.now().year + 100)]))
    meeting_time = forms.TimeField(widget=forms.TimeInput(attrs={"type": "time"}))
    meeting_description = forms.CharField(validators=[validators.RegexValidator(".{0,300}$", message="Description must be 300 or fewer characters.")], widget=forms.Textarea(attrs={'cols': 50, 'rows': 6, 'style': 'resize: vertical;'}), required=False)
    
    def clean(self):
        cleaned_data=super().clean()
        try:
            meeting_date = cleaned_data['meeting_date']
        except:
            return ValidationError("Date does not exist.")
        meeting_time = cleaned_data['meeting_time']
        meeting_datetime = datetime.combine(meeting_date, meeting_time)
        if meeting_datetime < datetime.now():
            raise ValidationError("Meeting must not be in the past")
        return cleaned_data

readmore_app/templates/readmore_app/club_library_member_view.html
{% extends parent_template|default:"base.html" %}
{% load static %}
{% load extras %}

{% block title %}
Readmore - {{ club.club_name }}
{% endblock %}

{% block content %}

<div style="display: flex; flex-direction: column; width: 80vw;">
<a style="margin-top: 50px; width:fit-content;" class="anchor_button" href="{% url 'readmore_app:club' club.club_id %}">Back To Club Home</a>
<div id="library">
    <center>
    <h1>My Club Library</h1>
    <h2>Club Books</h2>
    </center>
    {% if not club_library_isbns %}
    <h3>No Books Here</h3>
    {% endif %}
    <div class="table" id="book_search_results" style="overflow:unset; margin-right;">
        {% for shortlist in club_library %}
            {% for book in shortlist %}
            
                <div id="clubbook{{ book.id }}"  class="book_card_mv">
                <a class="book_search_link" href="{% url 'readmore_app:view_book' book.isbn13 %}">
                    <div style="width:20em;">
                    <div class="book_title" style="
                        display: flex;
                        position: absolute;
                        top: 0px;
                        width: 90%;
                        flex-direction: row;
                        flex-wrap: nowrap;
                        margin-top: 5%;
                        margin-left: 5%;
                        align-content: center;
                        align-items: flex-start;"">
                        <div ><img width="100px" height="140px" src="{{ book.small_thumbnail }}" alt="{{ book.title }} Cover Image" /></div>
                        <div >
                        
                        <p style="font-size:18px;">{{ book.title }}</p>
                        
                        </div>
                    </div>
                    <div style="margin-top: 60%;margin-bottom: 20px;">
                        <div style="display:flex; flex-direction: row;">
                            <div style="font-size:12px; width: 28%; margin-top: 12px;">
                                Author{{ book.authors|length|pluralize:"s" }}
                            </div>
                            <div style="width: 50%; margin-left:10px;">
                               
                                {% for author in book.authors %}
                                <p style="font-size:12px;">
                                <span style="font-size:12px;">{{ author }}</span>
                                </p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div>
                        <div colspan=2 style="font-size:12px;">ISBN: {{book.isbn13 }}</div>
                    </div>
                    </div>
                </a>
                <div><div align="center" colspan=2><div class="stars" style="--rating:{{ book.rating }};margin-bottom:5%;"></div></div></div>
                
            </div>
            
            {% endfor %}
        
        {% endfor %}
        
    </div>
</div>
</div>
{% endblock %}

{% block js %}
{% endblock %}

readmore_app/templates/readmore_app/create_book_forum_post.html
{% extends parent_template|default:"base.html" %}

{% block title %}
Readmore - Create Post
{% endblock %}

{% block content %}
<div class="form" style="margin-top:10%">
    <h1>Create a Post</h1>
    <form action="{% url 'readmore_app:create_book_forum_post' book.isbn13 %}" method="post">
        {% csrf_token %}
        <table id="formtable">
            {{ form.as_table }}
            <tr>
                <td colspan=2><center><input type="submit" value="Submit"></center></td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

readmore_app/templates/readmore_app/index.html
{% extends parent_template|default:"base.html" %}
{% load static %}
{% load extras %}


{% block title %}
Readmore - Index
{% endblock %}

{% block content %}
<div class="basic_card">
    <center>
    <h1>My Feed</h1>
    <div class="postlist">
    {% if not posts %}
    <p>No posts here.  Try joining some book clubs or adding friends.</p>
    {% else %}
        {% for post in posts %}
            <div class="clubpost">
                <div style="
                flex-direction: column;
                align-items: center;
                max-width: 89%;">
                    <div style="display:inline-flex;
                        justify-content: center;
                        max-width: 80%;
                        ">
                    <div>
                    <a href="{% url 'readmore_app:view_post' post.post_id %}" style="max-width:80;"><h2 style="margin: 10px;">{{ post.post_title }}</h2></a>
                    {% if post.post_club %}
                    <h5>Posted to: <a href="{% url 'readmore_app:club' post.post_club.club_id %}">{{ post.post_club.club_name }}</a></h5>
                    {% endif %}
                    {% if post.post_book_isbn %}
                    <h5>Posted to: <a href="{% url 'readmore_app:book_forum' post.post_book_isbn %}">"{% get_title post.post_book_isbn %}" Forum</a></h5>
                    {% endif %}
                    <h5 style="margin: 2px;">Post By: <a href="{% url 'readmore_app:profile' post.post_user.id %}">{{ post.post_user.username }}</a></h5>
                    <h6 style="margin: 2px;">{{ post.post_date|date:"m/d/Y h:i:s A" }}</h6>
                    </div>
                    <div style="max-width: 92%;word-break: break-word;">
                        <span class="likes">
                            <span id="nlikes{{ post.post_id }}">{{ post.post_likes.count }}</span>
                            <input id="likeimage{{post.post_id}}" onclick="doLike({{post.post_id}});" style="width: 20px;" type="image" src="{% if real_user in post.post_likes.all %}{% static 'readmore_app/thumbs_up.png' %}{% else %}{% static 'readmore_app/thumbs_up_gray.png' %}{% endif %}" />
                        </span>
                    </div>
                    </div>
                    <div>
                    {% if post.post_img %}
                        {% if post.post_rating %}<a href="{% url 'readmore_app:view_book' post.post_isbn %}">{% endif %}
                            <img style="max-width: 500px; width: 100%;-o-object-fit: contain; object-fit: contain; max-height: 400px;" src="{{ post.post_img }}"/>
                        {% if post.post_rating %}</a>{% endif %}
                    {% endif %}
                    </div>
                </div>
                
                
                {% if post.post_rating %}
                    <div align="center" colspan=3 style="
                    margin-top: 1%;
                    background: #b4b8cffc;
                    padding: 5px;
                    border-radius: 15px;
                    "><div class="stars" style="font-size: 250%; --rating:{{ post.post_rating|divide:2 }};"></div></div>
                {% endif %}
                {% if post.post_text %}
                <div class="post_text">
					{% autoescape off %}
					<p>{{ post.post_text }}</p>
					{% endautoescape %}
                </div>
                {% endif %}
                {% if post.post_user == real_user %}
                <button onclick="deletePost({{ post.post_id }});" class="anchor_button" style="float: right; margin-right: 10px; margin-top: 10px;">Delete This Post</button>
                {% endif %}
                
            </div>
        {% endfor %}
    {% endif %}
    </div>
    </center>
</div>
{% endblock %}

{% block js %}
function doLike(post_id) {
    const image = document.getElementById("likeimage" + post_id);
    const nlikes = document.getElementById("nlikes" + post_id);
    const xhrlike = new XMLHttpRequest();
    xhrlike.onload = function() {
        [new_image, num_likes] = this.responseText.split(' ');
        if (new_image == "unlike") {
            image.src = "/static/readmore_app/thumbs_up_gray.png";
        } else if (new_image == "like") {
            image.src = "/static/readmore_app/thumbs_up.png";
        }
        nlikes.innerHTML = num_likes;
    }
    xhrlike.open("GET", `/readmore/ajax/dolike/${post_id}/`);
    xhrlike.send();
}

function deletePost(post_id) {
    if (confirm("Are you sure you wish to delete this post?")) {
        const xhrdeletepost = new XMLHttpRequest();
        xhrdeletepost.onload = function() {
            if (this.responseText == "CONFIRM") {
                window.location.href = "/readmore/index/";
            }
        }
        xhrdeletepost.open("GET", `/readmore/ajax/delete_post/${post_id}/`);
        xhrdeletepost.send();
    }
}
{% endblock %}

readmore_app/templates/readmore_app/make_club.html
{% extends parent_template|default:"base.html" %}

{% block title %}
Readmore - Make a Book Club
{% endblock %}

{% block content %}
<div class="form">
    <h1>Make a Book Club</h1>
    <form action="{% url 'readmore_app:make_club' %}" method="post">
    {% csrf_token %}
        <table >
            {{ form.as_table }}
            <tr>
                <td style="text-align: left;" colspan=2><input type="submit" name="Make Book Club"></td>
            </tr>
        </table>
        
    </form>
</div>
{% endblock %}

readmore_app/templates/readmore_app/registration.html
{% extends parent_template|default:"base.html" %}

{% block title %}
Readmore - Register
{% endblock %}

{% block content %}
<main id="registration" style="padding-left: 0px;">
<div class="form">
    <h1>Register For an Account</h1>
    <form id="regform" action="{% url 'readmore_app:registration' %}" method="post">
    {% csrf_token %}
        <table>
        <tbody>
        <tr>
            <th><label for="id_username">Username:</label></th>
            <td><input type="text" name="username" required="" id="id_username"></td>
            <td>{{ form.username.errors }}</td>
        </tr>
        <tr>
            <th><label for="id_first_name">First name:</label></th>
            <td><input type="text" name="first_name" required="" id="id_first_name"></td>
            <td>{{ form.first_name.errors }}</td>
        </tr>
        <tr>
            <th><label for="id_last_name">Last name:</label></th>
            <td><input type="text" name="last_name" required="" id="id_last_name"></td>
            <td>{{ form.last_name.errors }}</td>
        </tr>
        <tr>
            <th><label for="id_email">Email:</label></th>
            <td><input type="email" name="email" required="" id="id_email"></td>
            <td>{{ form.email.errors }}</td>
        </tr>
        <tr>
            <th><label for="id_birthdate_month">Birthdate:</label></th>
            <td>
                {{ form.birthdate }}
            </td>
            <td>{{ form.birthdate.errors }}<ul id="date_error" class="errorlist"></ul></td>
        </tr>
        <tr>
            <th><label for="id_password">Password:</label></th>
            <td><input type="password" name="password" required="" id="id_password"></td>
            <td>{{ form.password.errors }}</td>
        </tr>
        <tr>
            <th><label for="id_confirm_password">Confirm password:</label></th>
            <td><input type="password" name="confirm_password" required="" id="id_confirm_password"></td>
            <td>{{ form.confirm_password.errors }}{{ form.non_field_errors }}</td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center;"><button onclick="checkDate();" class="submit" type="button">Register</button></td>
        </tr>
        </tbody>
        </table>
    </form>
</div>
{% endblock %}

{% block js %}
function checkDate(){
    error_info = document.getElementById("date_error");
    const month = document.getElementById("id_birthdate_month");
    const year = document.getElementById("id_birthdate_year");
    const day = document.getElementById("id_birthdate_day");
    const date = new Date(parseInt(year.value), parseInt(month.value) - 1 % 11 + 1, 0);
    
    console.log(day.value > date.getDate())
    if (day.value > date.getDate()){
        let li = document.createElement("li");
        li.innerHTML = "Date does not exist.";
        date_error.appendChild(li);
        return;
    } else {
        document.getElementById("regform").submit()
    }
}
{% endblock %}