Readmore/urls.py
from django.contrib import admin
from django.urls import path, include
from readmore_app import urls as readmore_app_urls
from readmore_app import views as readmore_app_views
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('readmore/', include(('readmore_app.urls', 'readmore_app'), namespace="readmore_app"), name="readmore_app_patterns"),
    path('', lambda request: redirect('readmore/', permanent=False)),
]

readmore_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index_full_link'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('login/<int:account_created>/', views.login, name='login_account_created'),
    path('logout/', views.logout, name='logout'),
    path('notifications/', views.notifications, name='notifications'),
    path('profile/<int:profile_id>/', views.profile, name='profile'),
    path('create_club/', views.create_club, name='create_club'),
    path('club/<int:club_id>/', views.club, name='club'),
    path('club_chat/<int:club_id>/', views.club_chat, name="club_chat"),
    path('friend_list/<int:profile_id>/', views.friend_list, name='friend_list'),
    path('user_search_results/', views.user_search_results, name="user_search_results"),
    path('book_clubs/', views.book_clubs, name="book_clubs"),
    path('club_members/<int:club_id>/', views.club_members, name='club_members'),
    path('invite_to_club/<int:club_id>/', views.invite_to_club, name='invite_to_club'),
    path('view_book/<str:book_isbn>/', views.view_book, name='view_book'),
    path('search_book/', views.search_book, name="search_book"),
    path('club_library/<int:club_id>/', views.club_library, name="club_library"),
    path('create_club_post/<int:club_id>/', views.create_club_post, name="create_club_post"),
    path('create_profile_post/<int:profile_id>/', views.create_profile_post, name="create_profile_post"),
	path('reading_log/', views.reading_log, name='reading_log'),
    path('reading_log/<int:profile_id>', views.reading_log_friend_view, name="reading_log_friend_view"),
    path('view_post/<int:post_id>/', views.view_post, name='view_post'),
    path('view_post/<int:post_id>/<int:highlight>/', views.view_post, name="view_post_highlighted_comment"),
    path('review_book/<str:book_isbn>/', views.create_review_post, name='create_review_post'),
    path('messages/', views.messages, name='messages_no_id'),
    path('messages/<int:friend_id>/', views.messages, name='messages'),
    path('book_forum/<str:book_isbn>/', views.book_forum, name='book_forum'),
    path('create_book_forum_post/<str:book_isbn>/', views.create_book_forum_post, name="create_book_forum_post"),
    path('club_schedule/<int:club_id>/', views.club_schedule, name='club_schedule'),
]

# AJAX url patterns
urlpatterns.extend(
    [
    path('ajax/notifications/<int:notification_id>/', views.delete_notification, name="delete_notification"),
    path('ajax/friend/', views.process_friend, name='process_friend'),
    path('ajax/get_friend_count/<int:user_id>/', views.get_friend_count, name="get_friend_count"),
    path('ajax/leave_club/<int:club_id>/', views.leave_club, name="leave_club"),
    path('ajax/kick_member/<int:club_id>/<int:member_id>/', views.kick_member, name="kick_member"),
    path('ajax/invite_member/<int:club_id>/<int:friend_id>/', views.invite_member, name="invite_member"),
    path('ajax/invite_nonfriend/<int:club_id>/<str:user>/', views.invite_nonfriend, name="invite_nonfriend"),
    path('ajax/join_club/<int:club_id>/', views.join_club, name="join_club"),
    path('ajax/remove_from_library/<int:club_id>/<int:club_book_id>/', views.remove_from_library, name='remove_from_library'),
    path('ajax/add_to_library/<int:club_id>/<str:isbn>/', views.add_to_library, name='add_to_library'),
    path('ajax/dolike/<int:post_id>/', views.do_like, name="do_like"),
    path('ajax/make_comment/<int:post_id>/', views.make_comment, name="make_comment"),
    path('ajax/remove_from_user_library/<int:book_id>/', views.remove_from_user_library, name='remove_from_user_library'),
    path('ajax/add_to_user_library/<str:isbn>/', views.add_to_user_library, name='add_to_user_library'),
    path('ajax/delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('ajax/save_bio/<int:user_id>/', views.save_bio, name='save_bio'),
    path('ajax/delete_meeting/<int:meeting_id>/', views.delete_meeting, name='delete_meeting'),
    ]
)

templates/base.html
{% load extras %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
        Readmore
      {% endblock %}
    </title>
    <link rel=stylesheet href="{% static 'readmore_app/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'readmore_app/readmore.ico' %}">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="container" >
      <div class="navbar navbar_wrapper">
        <div class="navbar">
          <div><h2 class="logo">readmore</h2></div>
          <div><img src="{% static 'readmore_app/logo_small.png' %}"></div>
        </div>
        <div class="navbar_links" style="padding-right:2%;">
          
          <a class="link" href="{% url 'readmore_app:index' %}">Home</a>
          {% if not user.is_authenticated %}
          <a class="link" href="{% url 'readmore_app:login' %}" >Login</a>
          <a class="link" href="{% url 'readmore_app:registration' %}">Register</a>
          {% else %}
          
          <a href="{% url 'readmore_app:logout' %}" >Logout</a>
          <div id="drop">
              {% num_notifications user.id as has_notifications %}
              <a  href="{% url 'readmore_app:profile' user.id %}" style="padding-bottom:17px;"><span id="notification_dot" style="color: red;">{% if has_notifications %}●{% endif %}</span>{{ user.username }}</a>
              <div id="dropdown">
                  <a class="dropaw" href="{% url 'readmore_app:notifications' %}">(<span id="num_notifications">{% num_notifications user.id %}</span>) Notifications</a>
                  <a class="dropaw" href="{% url 'readmore_app:reading_log' %}">My Reading Log</a>
                  <a class="dropaw" href="{% url 'readmore_app:messages_no_id' %}">Messages</a>
              </div>
          </div>
          <div style="padding: 0.5%;">
            <form style="display: flex; left: 0px; position: relative; top:7px; align-items: center;" class="link" method="POST" action="{% url 'readmore_app:user_search_results' %}">
              {% csrf_token %}
              <input type="image" width="20px" style="margin-right: 3%;" src="{% static 'readmore_app/logo_search.png' %}">
              <input type="text" placeholder="Search User" name="search_query" >
            </form>
          </div>
          {% endif %}

        </div>
      </div>
      
      <div class="content-container">
          {% if user.is_authenticated %}
          <div class="sidebar">
              <a href="{% url 'readmore_app:index' %}">Home</a>
              <a href="{% url 'readmore_app:book_clubs' %}">Book Clubs</a>
              <a href="{% url 'readmore_app:search_book' %}">Search Books</a>
          </div>
          <main style="margin:0;">
          {% endif %}
          {% block content %}
            Where content goes
          {% endblock %}
          </main>
      </div>
    </div>
  </body>
  <script>
    {% block js %}
    {% endblock %}
  </script>
</html>